version: "3.8"

services:
  # db:
  #   container_name: vzg_gradebook_db_dev
  #   image: postgres:16
  #   volumes:
  #     - vazgen-gradebook_volume_dev:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   networks:
  #     gradebook_network:
  #       ipv4_address: 199.0.0.122

  # pgadmin:
  #   container_name: vzg_gradebook_pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - gradebook_network

  # nginx:
  #   container_name: vzg_gradebook_nginx_dev
  #   build:
  #     dockerfile: ./docker/dockerfiles/Dockerfile-nginx
  #   ports:
  #     - "${NGINX_PORT}:80"
  #   volumes:
  #     - ./frontend/:/app/frontend
  #     - ./backend/static_files:/app/backend/server/static_files
  #     - ./docker/Nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - gradebook_network

  # backend:
  #   container_name: vzg_gradebook_backend_dev
  #   build:
  #     dockerfile: ./docker/dockerfiles/Dockerfile-backend
  #   entrypoint: /wsgi-entrypoint.sh
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./docker/Backend/dev-wsgi-entrypoint.sh:/wsgi-entrypoint.sh
  #     - ./backend:/app/backend
  #   expose:
  #     - 8000
  #   depends_on:
  #     - db
  #   networks:
  #     - gradebook_network

  backend:
    container_name: cubify_backend
    image: node:20.5.0-alpine
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./backend/node_modules:/app/backend/node_modules
    ports:
      - "${BACKEND_DEV_PORT}:3000"
    env_file:
      - .env
    command: sh -c "npm run start:dev"
    

  frontend:
    container_name: cubify_frontend
    image: node:20.5.0-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "${FRONTEND_DEV_PORT}:3000"
    env_file:
      - .env
    command: sh -c "npm run dev"

volumes:
  cubify_volume_dev:
