FROM node:20.11.1

WORKDIR /app/backend

COPY ./backend/package.json ./backend/package-lock.json ./

RUN npm install

COPY ./backend .

EXPOSE ${BACKEND_DEV_PORT} 5029

CMD ["npm", "run", "start:dev"]